### PR TITLE
Fix a memory leak in pushEntry

### LINKED ISSUE #103: Log results in memory leak until checkpoint is created
Not 100% sure if this is considered expected behaviour, but the following program

```haskell
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies    #-}

module Main where

import Control.Monad
import Data.Acid
import Data.Acid.Advanced
import Data.SafeCopy

data DB = DB

deriveSafeCopy 1 'base ''DB

myTx :: Update DB ()
myTx = return ()

makeAcidic ''DB ['myTx]

main :: IO ()
main = do
    db <- openLocalState DB
    replicateM_ 5 $ do
      replicateM_ 10000 $
        update' db $ MyTx
      createCheckpoint db
```

results in this memory profile (`+RTS -hy`)

with-checkpoints

### PR DESCRIPTION
**Pull request by adamgundry**
Fixes #103, I think. @edsko is it easy for you to check if this commit solves your original problem? Here are [before](https://github.com/acid-state/acid-state/files/2404720/leak-h.pdf) and [after](https://github.com/acid-state/acid-state/files/2404721/leak-fixed.pdf) profiles of a cut-down version on my machine.

Irrespective of the leak, the test program seems to run very slowly for me. I'm not sure if that is to be expected.

### CODE REVIEW

**Comment by edsko** [comment]
@adamgundry I won't be able to test this until after I come back. @adinapoli-iohk might be able to -- Alfredo, might be worth looking into this, as it would avoid having construct all those checkpoints.

And yes, the test program runs much slower than I expected also.

**Comment by adinapoli-iohk** [comment]
Right, roger (also, thanks @adamgundry for the quick turnaround 😉 ).

I suspect I will have to delegate to somebody else as profiling on my machine is currently busted (loooong story), but I can definitely test this on, say, a Linux VM with a bit of patience.

**Comment by adamgundry** [comment]
FWIW, my guess is that the slow performance is due to excessive contention on a lock, as `strace` indicates the program is doing lots of futex syscalls (at least in the `-threaded` case). Presumably this is contention between the main thread (which is generating trivial updates as fast as it can) and the background thread that performs the updates. It's not clear to me how representative this is of real-world applications, where the application would typically have work to do other than acid-state updates, and the updates themselves would do some work.

**Comment by stepcut** [comment]
I think the slowness is to be expected because each call to `update` has to wait until the event is durable before it can return. So there is a lot of waiting around for it to get through the OS onto the disk.

On the old acid-state website there used to be an example of how to perform perform a whole bunch of updates in a single transaction which dramatically speeds things up. But, in the real world, you seldom have an app that looks like that -- it only comes up in stress tests like this one.

**Comment by parsonsmatt** [comment]
Sorry that we hadn't responded earlier. This has indeed fixed one of the memory leaks in the Cardano codebase, but it didn't fix the one we *thought* was caused by it. Turns out it had a different cause altogether :smile: 

Thanks!

**Comment by adinapoli-iohk** [comment]
screen shot 2018-09-29 at 08 46 14

@adamgundry yup, to complement what Matt just said: it turns out we had also another (unrelated) leak, but once fixed, and once we applied also this patch, it finally produced the profile in the picture, _without_ artificially resorting in taking a checkpoint every now and again to mitigate the memory usage.

Good to go on our side!

**Comment by adamgundry** [comment]
Thanks for the feedback! It's good to know this fixed a leak, even if it wasn't the one you thought. :wink:

Regarding the performance question, let's consider this resolved for now. No doubt there are places where `acid-state` performance can be improved, but it probably isn't worth spending lots of effort on unrealistic stress tests, and any fixes are likely to be trickier than adding one exclamation mark.

**Pull request merged**
