### PR TITLE
Put acid-state under travis CI w/ nix

### PR DESCRIPTION
**Pull request by dmjio**
cc @Lemmih @stepcut

### CODE REVIEW

**Comment by stepcut** [comment]
Is this something that still seems like a good idea?

**Comment by LeifW** [comment]
I'd think so, but is the "with Nix" part necessary? It seems it'd be simple enough with cabal-install, e.g. https://github.com/jaor/iwlib/blob/master/.travis.yml
Or perhaps stack?

**Comment by dmjio** [comment]
Well, nix gives us a lot of GHC versions for free

**Comment by andreasabel** [comment]
I am afraid Travis CI is gone, but should parts of this PR salvaged for a nix installer? @dmjio, does the nix-part of this PR make sense by itself?  How would it be used?

**Comment by stepcut** [comment]
Travis CI is dead. The nix stuff is uninteresting as a stand-alone thing. acid-state is already in nixpkgs, and tools like cabal2nix make it trivial to create a standalone `default.nix` file if someone has a use case.

**Pull request closed without merging**
